iapiVersion: apps/v1
kind: Deployment
metadata:
  name: my-another-app
spec:
  selector:
    matchLabels:
      app: my-another-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-another-app
    spec:
      containers:
      - name: my-another-app
        image: nanajanashia/argocd-app:1.1
        ports:
        - containerPort: 8080

